# Generated by Django 3.1.7 on 2021-07-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_argyleuser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='argyleuser',
            name='token_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('expired', 'Expired')], max_length=10, null=True),
        ),
    ]
