# Generated by Django 3.1.7 on 2021-07-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_argyleuser_token_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argyleuser',
            name='token_status',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('expired', 'expired')], max_length=10, null=True),
        ),
    ]
